{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "Spec_data = pd.DataFrame.from_dict(data = {\"Vova\":\n",
    "            {\"user_id\": 259294833, \"last_online\" : 50, \"age\": -1, \"in_work\" : False},\n",
    "              \"Rodion\":\n",
    "            {\"user_id\": 11782046, \"last_online\" : 50, \"age\": -1, \"in_work\": False}}, orient = \"index\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Rodion     11782046\n",
       "Vova      259294833\n",
       "Name: user_id, dtype: int64"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Spec_data[(Spec_data[\"in_work\"] == False) & (Spec_data[\"user_id\"] != 0) & \n",
    "          (Spec_data[\"last_online\"] == Spec_data[\"last_online\"].min())]['user_id']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "import pandas as pd\n",
    "import re\n",
    "\n",
    "from resend import USER_MESSAGE_FILTERS, resend_message \n",
    "from telegram import ReplyKeyboardMarkup, InlineKeyboardButton, InlineKeyboardMarkup\n",
    "from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters,\n",
    "                          ConversationHandler, CallbackQueryHandler,  PicklePersistence)\n",
    "\n",
    "\n",
    "# Enable logging\n",
    "logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n",
    "                    level=logging.INFO)\n",
    "\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "(START, FIND_SPEC, ABOUT, FIND_SPEC_NOW, FIND_SPEC_LATER, SPEC_LIST, CHOOSE_AGE, PROBLEM_CATEGORY, \n",
    " QUESTION_CATEGORY, CHOOSING_ABOUT, MESSAGES) = range(11)\n",
    "\n",
    "\n",
    "def format_message(original_text):\n",
    "    \"\"\"\n",
    "    Format original message text from user (adds header)\n",
    "    :return: formatted original_text\n",
    "    \"\"\"\n",
    "    return original_text\n",
    "\n",
    "\n",
    "class Psy_Chat:\n",
    "    def __init__(self, specialist_df_path = None):\n",
    "        #self.Spec_data = pd.read_csv(specialist_df_path)\n",
    "        self.Spec_data = pd.DataFrame.from_dict(data = {\"Vova\":\n",
    "            {\"user_id\": 259294833, \"last_online\" : 50, \"age\": -1, \"in_work\" : False},\n",
    "              \"Rodion\":\n",
    "            {\"user_id\": 11782046, \"last_online\" : 50, \"age\": -1, \"in_work\": False}}, orient = \"index\")\n",
    "        \n",
    "    def start(self, update, context):\n",
    "        user = update.effective_user.first_name\n",
    "        logger.info(\"User %s goes to find_spec section.\", user)\n",
    "        # Build InlineKeyboard where each button has a displayed text\n",
    "        # and a string as callback_data\n",
    "        # The keyboard is a list of button rows, where each row is in turn\n",
    "        # a list (hence `[[...]]`).\n",
    "        keyboard = [\n",
    "            [InlineKeyboardButton('Найти специалиста', callback_data=str(FIND_SPEC)),\n",
    "             InlineKeyboardButton('О сервисе', callback_data=str(ABOUT))]\n",
    "        ]\n",
    "        reply_markup = InlineKeyboardMarkup(keyboard)\n",
    "        # Send message with text and appended InlineKeyboard\n",
    "        update.effective_chat.send_message(\n",
    "            text = \"\"\"Привет!\\n\\nЭтот бот поможет тебе справиться с депрессией или другими психологическими проблемами, которые тебя беспокоят!\\n\\nДавай начнем: выбери \"Найти специалиста\" или узнай о нас больше выбрав \"О сервисе\", так же ты можешь выбрать быструю помощь и мы найдем тебе ближайшего освободившегося специалиста\"\"\",\n",
    "            reply_markup=reply_markup\n",
    "    )\n",
    "        return START\n",
    "\n",
    "    \n",
    "    def stop(self, update, context):\n",
    "        \"\"\"Закончить общение с ботом по команде /stop\"\"\"\n",
    "        update.message.reply_text(\"\"\"Пока!\"\"\")\n",
    "\n",
    "        return ConversationHandler.END\n",
    "    \n",
    "    def done(self, update, context):\n",
    "        update.message.reply_text(\"\"\"Пока!\"\"\")\n",
    "        user_data = context.user_data\n",
    "        if 'choice' in user_data:\n",
    "            del user_data['choice']\n",
    "\n",
    "        print(user_data)\n",
    "\n",
    "        user_data.clear()\n",
    "        return ConversationHandler.END\n",
    "    \n",
    "    def find_spec(self, update, context):\n",
    "        user = update.effective_user.first_name\n",
    "        logger.info(\"User %s goes to find_spec section.\", user)\n",
    "        #Update message and keyboard\n",
    "        query = update.callback_query\n",
    "        bot = context.bot\n",
    "        keyboard = [\n",
    "            [InlineKeyboardButton('Быстрая помощь', callback_data=str(FIND_SPEC_NOW))],\n",
    "            [InlineKeyboardButton('Подобрать специалиста', callback_data=str(FIND_SPEC_LATER))],\n",
    "            [InlineKeyboardButton('Список специалистов', callback_data=str(SPEC_LIST))],\n",
    "        #         [InlineKeyboardButton('Назад', callback_data=str(START))]\n",
    "        ]\n",
    "        reply_markup = InlineKeyboardMarkup(keyboard)\n",
    "        bot.edit_message_text(\n",
    "            chat_id=query.message.chat_id,\n",
    "            message_id=query.message.message_id,\n",
    "            text=\"Мы можем помочь подобрать тебе специалиста сразу или в зависимости от характера твоей проблемы, либо ты можешь выбрать его самостоятельно из списка специалистов.\",\n",
    "            reply_markup=reply_markup\n",
    "            )\n",
    "\n",
    "        return FIND_SPEC\n",
    "    \n",
    "    def find_spec_later(self, update, context):\n",
    "    \n",
    "        #IN PROGRESS\n",
    "\n",
    "        # Section for complex search of specs\n",
    "        user = update.effective_user.first_name\n",
    "        logger.info(\"User %s goes to find_spec_later section.\", user) \n",
    "\n",
    "        context.query = update.callback_query\n",
    "        context.bot = context.bot\n",
    "\n",
    "        context.user_data = pd.DataFrame(index = [update.effective_user.id], columns = ['gender', 'age', 'city', 'problem_category', 'statement_category'])\n",
    "        for data in user_data.columns:\n",
    "            if data == 'gender':\n",
    "                def gender(update, context):\n",
    "                    keyboard = [\n",
    "                        [InlineKeyboardButton('Мужской', callback_data = \"Мужской\"),\n",
    "                         InlineKeyboardButton('Женский', callback_data = \"Женский\")]\n",
    "                    ]\n",
    "                    reply_markup = InlineKeyboardMarkup(keyboard)\n",
    "                    # Send message with text and appended InlineKeyboard\n",
    "                    update.effective_chat.send_message(\n",
    "                        text = \"Твой пол?\",\n",
    "                        reply_markup=reply_markup\n",
    "                    )\n",
    "                    print(update.callback_query)\n",
    "                    while update.inline_query == None:\n",
    "                        print(update.callback_query)\n",
    "                        user_data.loc[update.effective_user.id, 'gender'] = update.inline_query.query\n",
    "                        print(user_data.loc[update.effective_user.id, 'gender'])\n",
    "        pass\n",
    "    \n",
    "    def spec_list(self, update, context):\n",
    "        pass\n",
    "    \n",
    "    def gender(self, update, context):\n",
    "        r\"\"\"Пол\"\"\"\n",
    "        reply_keyboard_loc = [['М', 'Ж']]\n",
    "        markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "\n",
    "        update.message.reply_text(\"\"\"Выберите ваш пол.\"\"\", reply_markup=markup_loc)\n",
    "        return CHOOSE_AGE\n",
    "\n",
    "\n",
    "    def age(self, update, context):\n",
    "        r\"\"\"Возраст\"\"\"\n",
    "        reply_keyboard_loc = [['< 16', '16-22', '22-40', \"> 40\"]]\n",
    "        markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "        update.message.reply_text(\"\"\"Выберите ваш возраст.\"\"\", reply_markup=markup_loc)\n",
    "\n",
    "        return PROBLEM_CATEGORY\n",
    "\n",
    "    def problem_category(self, update, context):\n",
    "        r\"\"\"Выбрать проблему из предложенных типов\"\"\"\n",
    "        reply_keyboard_loc = [['Семья', 'Друзья', 'Отношения', \"Работа\", \"Учеба\", \"Другое\"]]\n",
    "        markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "        update.message.reply_text(\"\"\"К какой категории Вы могли бы отнести свою психологическую проблему?\"\"\", reply_markup=markup_loc)\n",
    "\n",
    "        return QUESTION_CATEGORY\n",
    "\n",
    "    def statement_category(self, update, context):\n",
    "        r\"\"\"Выбрать утверждение из предложенных типов\"\"\"\n",
    "        reply_keyboard_loc = [['Я запутался/лась', 'Мне не интересно или скучно', 'Я устал', \"Меня никто не слушает\",\n",
    "                               \"Что делать дальше\", \"Как сделать правильный выбор\", \"Другое\"]]\n",
    "        markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "        update.message.reply_text(\"\"\"Какие утверждения или вопросы подходят Вам наиболее всего?\"\"\", reply_markup=markup_loc)\n",
    "\n",
    "        return WAITING_TIME\n",
    "\n",
    "    def find_spec_now(self, update, context):\n",
    "        r\"\"\"Подбор специалиста сразу\"\"\"\n",
    "        query = update.callback_query\n",
    "        bot = context.bot\n",
    "        keyboard = [\n",
    "            [InlineKeyboardButton('Отменить поиск', callback_data=str(START))]\n",
    "        ]\n",
    "        reply_markup = InlineKeyboardMarkup(keyboard)\n",
    "        bot.edit_message_text(\n",
    "            chat_id=query.message.chat_id,\n",
    "            message_id=query.message.message_id,\n",
    "            text=\"Мы уже ищем специалиста. Ожидайте...\",\n",
    "            reply_markup=reply_markup\n",
    "        )\n",
    "        \n",
    "        user_id = update._effective_user.id\n",
    "        Best_specialist = self.Spec_data[(self.Spec_data[\"in_work\"] == False) &\n",
    "                                         (self.Spec_data[\"user_id\"] != user_id)]['user_id']\n",
    "        \n",
    "        keyboard = [\n",
    "            [InlineKeyboardButton('Принять клиента', callback_data = \"Принять клиента\"),\n",
    "            InlineKeyboardButton('Отменить прием', callback_data = \"Отменить прием\")]\n",
    "        ]\n",
    "        reply_markup = InlineKeyboardMarkup(keyboard)\n",
    "        if len(Best_specialist) > 0:\n",
    "            for paired_user_id in Best_specialist:       \n",
    "                bot.sendMessage(paired_user_id, text= 'Приймите клиента если у вас есть возможность', reply_markup)\n",
    "                if update.Message.ReplyToMessage.Text.Contains(\"Принять клиента\"):\n",
    "                    \n",
    "                \n",
    "            print(update)\n",
    "        if user_id == 259294833:\n",
    "            paired_user_id = 11782046\n",
    "        else:\n",
    "            paired_user_id = 259294833\n",
    "            \n",
    "        bot.sendMessage(user_id, text = 'Соединение установленно')\n",
    "        bot.sendMessage(paired_user_id, text= 'Соединение установленно')\n",
    "        \n",
    "        return MESSAGES\n",
    "    \n",
    "    def message(self, update, context):\n",
    "\n",
    "        user_id = update._effective_user.id\n",
    "        bot = context.bot\n",
    "        #self.Spec_data[self.Spec_data[\"user_id\"] != user_id]\n",
    "        if user_id == 259294833:\n",
    "            paired_user_id = 11782046\n",
    "        else:\n",
    "            paired_user_id = 259294833\n",
    "            \n",
    "        if paired_user_id and paired_user_id > 0:\n",
    "            logger.info('Resending ' + str(update.message.text))\n",
    "            try:\n",
    "                resend_message(bot, update, paired_user_id, format_message)\n",
    "                print(\"resended\")\n",
    "            except Exception as E:\n",
    "                print(\"fail \"+ str(E))\n",
    "                bot.sendMessage(user_id, text='DISCONNECTED',\n",
    "                                #reply_markup=KEYBOARD_MARKUP\n",
    "                               )\n",
    "        else:\n",
    "            print(\"FAIL\")\n",
    "\n",
    "    def about(self, update, context):\n",
    "        r\"\"\"О нас\"\"\"\n",
    "        reply_keyboard_loc = [['О сервисе', 'Стоимость услуг', 'Отзывы', \"О нас пишут\", \"FAQ\" ]]\n",
    "        markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "        update.message.reply_text(\"\"\"PsyHelp - бот психологической поддержки\"\"\", reply_markup=markup_loc)\n",
    "\n",
    "        return CHOOSING_ABOUT\n",
    "\n",
    "    def error(self, update, context):\n",
    "        \"\"\"Log Errors caused by Updates.\"\"\"\n",
    "        logger.warning('Update \"%s\" caused error \"%s\"', update, context.error)\n",
    "        \n",
    "    def run(self):\n",
    "        my_persistence = PicklePersistence(filename='my_file')\n",
    "        \n",
    "        updater = Updater(\"984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs\", persistence=my_persistence,\n",
    "                          use_context=True)\n",
    "        \n",
    "        # Get the dispatcher to register handlers\n",
    "        dp = updater.dispatcher\n",
    "\n",
    "        conv_handler = ConversationHandler(\n",
    "            entry_points=[CommandHandler('start', self.start)],\n",
    "            states={\n",
    "                START: [CallbackQueryHandler(self.find_spec, pattern='^' + str(FIND_SPEC) + '$'),\n",
    "                       CallbackQueryHandler(self.about, pattern='^' + str(ABOUT) + '$')],\n",
    "\n",
    "                FIND_SPEC: [CallbackQueryHandler(self.find_spec_now, pattern='^' + str(FIND_SPEC_NOW) + '$'),\n",
    "                           CallbackQueryHandler(self.find_spec_later, pattern='^' + str(FIND_SPEC_LATER) + '$'),\n",
    "                           CallbackQueryHandler(self.spec_list, pattern='^' + str(SPEC_LIST) + '$')],\n",
    "                \n",
    "                MESSAGES: [MessageHandler(filters = Filters.text | Filters.audio | Filters.document | Filters.photo | Filters.sticker | Filters.video | Filters.voice | Filters.contact | Filters.location | Filters.venue\n",
    "                           ,callback= self.message)]\n",
    "\n",
    "    #             FIND_SPEC_NOW: [CallbackQueryHandler(start, pattern='^' + str(START) + '$')],\n",
    "\n",
    "    #             ABOUT: [CallbackQueryHandler(start_over, pattern='^' + str(ONE) + '$'),\n",
    "    #                      CallbackQueryHandler(end, pattern='^' + str(TWO) + '$')]\n",
    "            },\n",
    "            fallbacks=[CommandHandler('start', self.start),\n",
    "                      CallbackQueryHandler(self.start, pattern='^' + str(START) + '$')\n",
    "                      ]\n",
    "        )    \n",
    "\n",
    "        dp.add_handler(conv_handler)\n",
    "        print(dp.handlers)\n",
    "        # log all errors\n",
    "        dp.add_error_handler(self.error)\n",
    "\n",
    "        # Start the Bot\n",
    "        updater.start_polling()\n",
    "\n",
    "        # Run the bot until you press Ctrl-C or the process receives SIGINT,\n",
    "        # SIGTERM or SIGABRT. This should be used most of the time, since\n",
    "        # start_polling() is non-blocking and will stop the bot gracefully.\n",
    "        updater.idle()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "a = Psy_Chat()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\telegram\\ext\\conversationhandler.py:215: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.\n",
      "  warnings.warn(\"If 'per_message=False', 'CallbackQueryHandler' will not be \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{0: [<telegram.ext.conversationhandler.ConversationHandler object at 0x000001D33352ABC8>]}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-12-16 16:29:11,707 - __main__ - INFO - User Родион goes to find_spec section.\n",
      "2019-12-16 16:29:18,859 - __main__ - INFO - User Родион goes to find_spec section.\n",
      "2019-12-16 16:29:24,584 - __main__ - INFO - Resending {'message_id': 1177, 'date': 1576492177, 'chat': {'id': 11782046, 'type': 'private', 'username': 'Rpl123', 'first_name': 'Родион'}, 'text': '123123123123', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 11782046, 'first_name': 'Родион', 'is_bot': False, 'username': 'Rpl123', 'language_code': 'ru'}}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "i_am_sending_text\n",
      "123123123123\n",
      "resended\n"
     ]
    }
   ],
   "source": [
    "a.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "d = {'update_id': 716208453, 'callback_query': {'id': '50603506090824630', 'chat_instance': '6628734935264516976', 'message': \n",
    "    {'message_id': 937, 'date': 1576484478, 'chat': {'id': 11782046, 'type': 'private', 'username': 'Rpl123', 'first_name': 'Родион'}\n",
    "     , 'edit_date': 1576484480, 'text': 'Мы можем помочь подобрать тебе специалиста сразу или в зависимости от характера твоей проблемы, либо ты можешь выбрать его самостоятельно из списка специалистов.', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'reply_markup': {'inline_keyboard': [[{'text': 'Быстрая помощь', 'callback_data': '3'}], [{'text': 'Подобрать специалиста', 'callback_data': '4'}], [{'text': 'Список специалистов', 'callback_data': '5'}]]}, 'from': {'id': 984001690, 'first_name': 'ПомощьПсихолога', 'is_bot': True, 'username': 'HelpPsychoRu_bot'}}, 'data': '3', 'from': {'id': 11782046, 'first_name': 'Родион', 'is_bot': False, 'username': 'Rpl123', 'language_code': 'ru'}}, '_effective_user': {'id': 11782046, 'first_name': 'Родион', 'is_bot': False, 'username': 'Rpl123', 'language_code': 'ru'}, '_effective_chat': {'id': 11782046, 'type': 'private', 'username': 'Rpl123', 'first_name': 'Родион'}}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'message_id': 937,\n",
       " 'date': 1576484478,\n",
       " 'chat': {'id': 11782046,\n",
       "  'type': 'private',\n",
       "  'username': 'Rpl123',\n",
       "  'first_name': 'Родион'},\n",
       " 'edit_date': 1576484480,\n",
       " 'text': 'Мы можем помочь подобрать тебе специалиста сразу или в зависимости от характера твоей проблемы, либо ты можешь выбрать его самостоятельно из списка специалистов.',\n",
       " 'entities': [],\n",
       " 'caption_entities': [],\n",
       " 'photo': [],\n",
       " 'new_chat_members': [],\n",
       " 'new_chat_photo': [],\n",
       " 'delete_chat_photo': False,\n",
       " 'group_chat_created': False,\n",
       " 'supergroup_chat_created': False,\n",
       " 'channel_chat_created': False,\n",
       " 'reply_markup': {'inline_keyboard': [[{'text': 'Быстрая помощь',\n",
       "     'callback_data': '3'}],\n",
       "   [{'text': 'Подобрать специалиста', 'callback_data': '4'}],\n",
       "   [{'text': 'Список специалистов', 'callback_data': '5'}]]},\n",
       " 'from': {'id': 984001690,\n",
       "  'first_name': 'ПомощьПсихолога',\n",
       "  'is_bot': True,\n",
       "  'username': 'HelpPsychoRu_bot'}}"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "d['callback_query']['message']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['update_id', 'callback_query', '_effective_user', '_effective_chat'])"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "d.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "# -*- coding: utf-8 -*-\n",
    "# This program is dedicated to the public domain under the CC0 license.\n",
    "\n",
    "\"\"\"\n",
    "First, a few callback functions are defined. Then, those functions are passed to\n",
    "the Dispatcher and registered at their respective places.\n",
    "Then, the bot is started and runs until we press Ctrl-C on the command line.\n",
    "Usage:\n",
    "Example of a bot-user conversation using ConversationHandler.\n",
    "Send /start to initiate the conversation.\n",
    "Press Ctrl-C on the command line or send a signal to the process to stop the\n",
    "bot.\n",
    "\"\"\"\n",
    "\n",
    "import logging\n",
    "\n",
    "from telegram import ReplyKeyboardMarkup\n",
    "from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters,\n",
    "                          ConversationHandler)\n",
    "\n",
    "# Enable logging\n",
    "logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n",
    "                    level=logging.INFO)\n",
    "\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "CHOOSING, TYPING_REPLY, TYPING_CHOICE = range(3)\n",
    "\n",
    "reply_keyboard = [['Age', 'Favourite colour'],\n",
    "                  ['Number of siblings', 'Something else...'],\n",
    "                  ['Done']]\n",
    "markup = ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True)\n",
    "\n",
    "\n",
    "reply_keyboard_2 = [\"\"]\n",
    "def facts_to_str(user_data):\n",
    "    facts = list()\n",
    "\n",
    "    for key, value in user_data.items():\n",
    "        facts.append('{} - {}'.format(key, value))\n",
    "\n",
    "    return \"\\n\".join(facts).join(['\\n', '\\n'])\n",
    "\n",
    "\n",
    "def start(update, context):\n",
    "    update.message.reply_text(\n",
    "        \"Hi! My name is Doctor Botter. I will hold a more complex conversation with you. \"\n",
    "        \"Why don't you tell me something about yourself?\",\n",
    "        reply_markup=markup)\n",
    "\n",
    "    return CHOOSING\n",
    "\n",
    "\n",
    "def regular_choice(update, context):\n",
    "    text = update.message.text\n",
    "    context.user_data['choice'] = text\n",
    "    update.message.reply_text(\n",
    "        'Your {}? Yes, I would love to hear about that!'.format(text.lower()))\n",
    "\n",
    "    return TYPING_REPLY\n",
    "\n",
    "\n",
    "def custom_choice(update, context):\n",
    "    update.message.reply_text('Alright, please send me the category first, '\n",
    "                              'for example \"Most impressive skill\"')\n",
    "\n",
    "    return TYPING_CHOICE\n",
    "\n",
    "\n",
    "def received_information(update, context):\n",
    "    user_data = context.user_data\n",
    "    text = update.message.text\n",
    "    category = user_data['choice']\n",
    "    user_data[category] = text\n",
    "    del user_data['choice']\n",
    "\n",
    "    update.message.reply_text(\"Neat! Just so you know, this is what you already told me:\"\n",
    "                              \"{} You can tell me more, or change your opinion\"\n",
    "                              \" on something.\".format(facts_to_str(user_data)),\n",
    "                              reply_markup=markup)\n",
    "\n",
    "    return CHOOSING\n",
    "\n",
    "\n",
    "def done(update, context):\n",
    "    user_data = context.user_data\n",
    "    if 'choice' in user_data:\n",
    "        del user_data['choice']\n",
    "\n",
    "    update.message.reply_text(\"I learned these facts about you:\"\n",
    "                              \"{}\"\n",
    "                              \"Until next time!\".format(facts_to_str(user_data)))\n",
    "\n",
    "    user_data.clear()\n",
    "    return ConversationHandler.END\n",
    "\n",
    "\n",
    "def error(update, context):\n",
    "    \"\"\"Log Errors caused by Updates.\"\"\"\n",
    "    logger.warning('Update \"%s\" caused error \"%s\"', update, context.error)\n",
    "\n",
    "\n",
    "def main():\n",
    "    # Create the Updater and pass it your bot's token.\n",
    "    # Make sure to set use_context=True to use the new context based callbacks\n",
    "    # Post version 12 this will no longer be necessary\n",
    "    updater = Updater(\"984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs\", use_context=True)\n",
    "\n",
    "    # Get the dispatcher to register handlers\n",
    "    dp = updater.dispatcher\n",
    "\n",
    "    # Add conversation handler with the states CHOOSING, TYPING_CHOICE and TYPING_REPLY\n",
    "    conv_handler = ConversationHandler(\n",
    "        entry_points=[CommandHandler('start', start)],\n",
    "\n",
    "        states={\n",
    "            CHOOSING: [MessageHandler(Filters.regex('^(Age|Favourite colour|Number of siblings)$'),\n",
    "                                      regular_choice),\n",
    "                       MessageHandler(Filters.regex('^Something else...$'),\n",
    "                                      custom_choice)\n",
    "                       ],\n",
    "\n",
    "            TYPING_CHOICE: [MessageHandler(Filters.text,\n",
    "                                           regular_choice)\n",
    "                            ],\n",
    "\n",
    "            TYPING_REPLY: [MessageHandler(Filters.text,\n",
    "                                          received_information),\n",
    "                           ],\n",
    "        },\n",
    "\n",
    "        fallbacks=[MessageHandler(Filters.regex('^Done$'), done)]\n",
    "    )\n",
    "\n",
    "    dp.add_handler(conv_handler)\n",
    "\n",
    "    # log all errors\n",
    "    dp.add_error_handler(error)\n",
    "\n",
    "    # Start the Bot\n",
    "    updater.start_polling()\n",
    "\n",
    "    # Run the bot until you press Ctrl-C or the process receives SIGINT,\n",
    "    # SIGTERM or SIGABRT. This should be used most of the time, since\n",
    "    # start_polling() is non-blocking and will stop the bot gracefully.\n",
    "    updater.idle()\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-12-05 22:52:32,858 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555C50A48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-05 22:52:37,876 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEEF88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-05 22:52:42,877 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556007108>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-05 22:52:47,879 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE888>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-05 22:52:47,879 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE888>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-05 22:52:53,893 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555C50908>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-05 22:52:58,905 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655620FEC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-05 22:53:03,906 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655620F188>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-05 22:53:08,914 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655620FB08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-05 22:53:08,914 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655620FB08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:05:46,544 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555E73608>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:05:51,546 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555E73148>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:05:56,553 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A44908>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:01,560 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B4E948>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:06:01,560 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B4E948>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:06:07,578 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D98E88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:12,585 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655480CEC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:17,592 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE308>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:22,604 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEEB48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-12-08 09:06:22,604 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEEB48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:06:29,111 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D98CC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:34,123 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B4E188>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:39,130 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655620FD08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:44,137 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000165560070C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:06:44,137 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000165560070C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:06:51,393 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE8C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:06:56,400 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B4EB08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:01,412 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555C50988>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:06,419 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609C3C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:07:06,419 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609C3C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:07:14,807 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE588>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:19,810 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555EB3808>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:24,822 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556040B48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:29,829 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556040A88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:07:29,829 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556040A88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:07:39,921 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609CD88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:44,923 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655626AE88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:07:49,935 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609C888>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-12-08 09:07:54,937 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AA13C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:07:54,937 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AA13C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:08:07,546 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x00000165560406C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:08:12,553 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609C8C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:08:17,565 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609C348>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:08:22,572 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609CE08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:08:22,572 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609CE08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:08:38,967 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556040C08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:08:43,967 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556007E48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:08:48,970 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655480CEC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:08:53,971 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE648>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:08:53,971 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE648>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:09:16,071 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555C50C08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:09:21,083 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556007608>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:09:26,084 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A6C348>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:09:31,096 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B4EB08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:09:31,096 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B4EB08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:10:01,736 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEEC08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:10:06,748 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556007A88>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-12-08 09:10:11,771 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655620F4C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:10:16,783 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AA1248>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:10:16,783 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AA1248>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:11:00,236 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B702C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:11:05,237 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D859C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:11:10,250 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D85648>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:11:15,262 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A655C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:11:15,262 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A655C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:11:50,284 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D85108>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:11:55,296 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D85048>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:12:00,309 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555EF0CC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:12:05,316 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555EF0788>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:12:05,316 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555EF0788>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:12:40,328 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A65888>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:12:45,340 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A44908>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:12:50,347 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555A65CC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:12:55,354 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555E73E48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:12:55,354 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555E73E48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:13:30,392 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D85188>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-12-08 09:13:35,399 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEEEC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:13:40,411 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEEB08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:13:45,423 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE048>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:13:45,423 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE048>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:14:20,446 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555D85DC8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:14:25,453 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556007808>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:14:30,460 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555AEE148>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:14:35,472 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555C50B08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:14:35,472 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555C50B08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-08 09:15:10,494 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016555B701C8>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:15:15,501 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609C248>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:15:20,503 - telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x0000016556007A08>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates\n",
      "2019-12-08 09:15:25,510 - telegram.ext.updater - ERROR - Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609CC48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\n",
      "2019-12-08 09:15:25,510 - __main__ - WARNING - Update \"None\" caused error \"urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs/getUpdates (Caused by ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x000001655609CC48>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)'))\"\n",
      "2019-12-09 16:25:09,290 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...\n"
     ]
    }
   ],
   "source": [
    "import logging\n",
    "\n",
    "import re\n",
    "\n",
    "from telegram import ReplyKeyboardMarkup\n",
    "from telegram.ext import (Updater, CommandHandler, MessageHandler, Filters,\n",
    "                          ConversationHandler)\n",
    "\n",
    "# Enable logging\n",
    "logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',\n",
    "                    level=logging.INFO)\n",
    "\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "CHOOSING, STEP_2_FIND_SPEC , CHOOSE_AGE, PROBLEM_CATEGORY, QUESTION_CATEGORY = range(5)\n",
    "FIND_SPEC_NOW, CHOOSING_ABOUT = range(5,7)\n",
    "\n",
    "\n",
    "\n",
    "def start(update, context):\n",
    "    reply_keyboard = [['Найти специалиста', 'О сервисе']]\n",
    "\n",
    "    markup = ReplyKeyboardMarkup(reply_keyboard, one_time_keyboard=True)\n",
    "    update.message.reply_text(\n",
    "        \"\"\"Привет! Этот бот поможет тебе справиться с депрессией или другими психологическими проблемами, которые тебя беспокоят! \n",
    "        Давай начнем: выбери \"Найти специалиста\" или узнай о нас больше выбрав \"О сервисе\", \n",
    "        так же ты можешь выбрать быструю помощь и мы найдем тебе ближайшего освободившегося специалиста\"\"\",\n",
    "        reply_markup=markup)\n",
    "\n",
    "    return CHOOSING\n",
    "\n",
    "def stop(update, context):\n",
    "    \"\"\"Закончить общение с ботом по команде /stop\"\"\"\n",
    "    update.message.reply_text(\"\"\"Пока!\"\"\")\n",
    "    \n",
    "    return ConversationHandler.END\n",
    "\n",
    "def done(update, context):\n",
    "    update.message.reply_text(\"\"\"Пока!\"\"\")\n",
    "    user_data = context.user_data\n",
    "    if 'choice' in user_data:\n",
    "        del user_data['choice']\n",
    "\n",
    "    print(user_data)\n",
    "\n",
    "    user_data.clear()\n",
    "    return ConversationHandler.END\n",
    "\n",
    "def Find_Spec(update, context):\n",
    "    r\"\"\"найи специалиста выбор из двух альтернатив и переход к след шагу\"\"\"\n",
    "    reply_keyboard_loc = [['Быстрая помощь','Подобрать', 'Список Специалистов']]\n",
    "\n",
    "    markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "    \n",
    "    update.message.reply_text(\n",
    "        \"\"\"Мы можем помочь подобрать Вам специалиста сразу или в зависимости от характера вашей проблемы, \n",
    "        либо вы можете выбрать его самостоятельно из списка специалистов.\"\"\",\n",
    "        reply_markup=markup_loc)\n",
    "    \n",
    "    return STEP_2_FIND_SPEC\n",
    "\n",
    "def Pol(update, context):\n",
    "    r\"\"\"Пол\"\"\"\n",
    "    reply_keyboard_loc = [['М', 'Ж']]\n",
    "    markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "    \n",
    "    update.message.reply_text(\"\"\"Выберите ваш пол.\"\"\", reply_markup=markup_loc)\n",
    "    return CHOOSE_AGE\n",
    "\n",
    "\n",
    "def Age(update, context):\n",
    "    r\"\"\"Возраст\"\"\"\n",
    "    reply_keyboard_loc = [['< 16', '16-22', '22-40', \"> 40\"]]\n",
    "    markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "    update.message.reply_text(\"\"\"Выберите ваш возраст.\"\"\", reply_markup=markup_loc)\n",
    "    \n",
    "    return PROBLEM_CATEGORY\n",
    "\n",
    "def Problem_Category(update, context):\n",
    "    r\"\"\"Выбрать проблему из предложенных типов\"\"\"\n",
    "    reply_keyboard_loc = [['Семья', 'Друзья', 'Отношения', \"Работа\", \"Учеба\", \"Другое\"]]\n",
    "    markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "    update.message.reply_text(\"\"\"К какой категории Вы могли бы отнести свою психологическую проблему?\"\"\", reply_markup=markup_loc)\n",
    "    \n",
    "    return QUESTION_CATEGORY\n",
    "\n",
    "def Question_Category(update, context):\n",
    "    r\"\"\"Выбрать вопрос из предложенных типов\"\"\"\n",
    "    reply_keyboard_loc = [['Я запутался/лась', 'Мне не интересно или скучно', 'Я устал', \"Меня никто не слушает\",\n",
    "                           \"Что делать дальше\", \"Как сделать правильный выбор\", \"Другое\"]]\n",
    "    markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "    update.message.reply_text(\"\"\"Какие утверждения или вопросы подходят Вам наиболее всего?\"\"\", reply_markup=markup_loc)\n",
    "    \n",
    "    return WAITING_TIME\n",
    "\n",
    "def find_spec_now(update, contex):\n",
    "    r\"\"\"Подбор специалиста сразу\"\"\"\n",
    "    update.message.reply_text(\"\"\"Мы уже ищем специалиста. Ожидайте...\"\"\")\n",
    "    ''' Нужно допилить алгоритм быстрого поиска'''\n",
    "    def fast_search(update, context):\n",
    "        pass\n",
    "    \n",
    "    return FIND_SPEC_NOW\n",
    "\n",
    "def about(update, context):\n",
    "    r\"\"\"О нас\"\"\"\n",
    "    reply_keyboard_loc = [['О сервисе', 'Стоимость услуг', 'Отзывы', \"О нас пишут\", \"FAQ\" ]]\n",
    "    markup_loc = ReplyKeyboardMarkup(reply_keyboard_loc, one_time_keyboard=True)\n",
    "    update.message.reply_text(\"\"\"PsyHelp - бот психологической поддержки\"\"\", reply_markup=markup_loc)\n",
    "    \n",
    "    return CHOOSING_ABOUT\n",
    "    \n",
    "def error(update, context):\n",
    "    \"\"\"Log Errors caused by Updates.\"\"\"\n",
    "    logger.warning('Update \"%s\" caused error \"%s\"', update, context.error)\n",
    "\n",
    "\n",
    "def main():\n",
    "    # Create the Updater and pass it your bot's token.\n",
    "    # Make sure to set use_context=True to use the new context based callbacks\n",
    "    # Post version 12 this will no longer be necessary\n",
    "    updater = Updater(\"984001690:AAHvJPz7H064B0J9CTJE-243qYMSOVhisPs\", use_context=True)\n",
    "\n",
    "    # Get the dispatcher to register handlers\n",
    "    dp = updater.dispatcher\n",
    "\n",
    "    # Add conversation handler with the states CHOOSING, TYPING_CHOICE and TYPING_REPLY\n",
    "    conv_handler = ConversationHandler(\n",
    "        entry_points=[CommandHandler('start', start)],\n",
    "\n",
    "        states={\n",
    "            CHOOSING: [MessageHandler(Filters.regex('^Найти специалиста$'),\n",
    "                                      Find_Spec),\n",
    "                       MessageHandler(Filters.regex('^О сервисе$'),\n",
    "                                      about),\n",
    "                       ],\n",
    "            STEP_2_FIND_SPEC: [ MessageHandler(Filters.regex('^Быстрая помощь$'),\n",
    "                                      find_spec_now),\n",
    "                               MessageHandler(Filters.regex('^Подобрать$'),\n",
    "                                      Pol),\n",
    "                       MessageHandler(Filters.regex('^Список Специалистов$'),\n",
    "                                      Pol)\n",
    "            ],\n",
    "\n",
    "            CHOOSE_AGE: [MessageHandler(Filters.regex('^.*$'), Age) \n",
    "                            ],\n",
    "            \n",
    "            PROBLEM_CATEGORY: [MessageHandler(Filters.regex('^.*$'), Problem_Category)\n",
    "                            ],\n",
    "            \n",
    "            QUESTION_CATEGORY: [MessageHandler(Filters.regex('^.*$'), Question_Category)\n",
    "                            ],\n",
    "        },\n",
    "\n",
    "        fallbacks=[MessageHandler(Filters.regex('^Done$'), done),\n",
    "                  CommandHandler('stop', stop)]\n",
    "    )\n",
    "\n",
    "    dp.add_handler(conv_handler)\n",
    "\n",
    "    # log all errors\n",
    "    dp.add_error_handler(error)\n",
    "\n",
    "    # Start the Bot\n",
    "    updater.start_polling()\n",
    "\n",
    "    # Run the bot until you press Ctrl-C or the process receives SIGINT,\n",
    "    # SIGTERM or SIGABRT. This should be used most of the time, since\n",
    "    # start_polling() is non-blocking and will stop the bot gracefully.\n",
    "    updater.idle()\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
